# .github/workflows/youtube_upload.yml
name: YouTube Auto Upload

on:
  schedule:
    # UTC（協定世界時）で指定します。日本時間(JST)はUTC+9時間です。
    # 例: 毎日 日本時間の午前8時と午後8時に実行 (UTCで前日の23時と当日の11時)
    - cron: '0 23 * * *' # UTC 23:00 (JST 08:00)
    - cron: '0 11 * * *' # UTC 11:00 (JST 20:00)
  workflow_dispatch: # GitHub UIから手動で実行できるようにする

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # スクリプトに適合するPythonバージョンを指定

      - name: Install system dependencies (ImageMagick)
        run: |
          sudo apt-get update -qq
          # imagemagick-dev が見つからない場合があるため、libmagickwand-dev を試す
          # これが imagemagick とその開発ファイルを含むことが多い
          sudo apt-get install -y imagemagick libmagickwand-dev
          # ImageMagickのポリシー設定を修正 (PDF/動画処理を許可)
          # パスが環境によって異なる可能性があるので、いくつかの一般的なパスを試す
          POLICY_FILES=("/etc/ImageMagick-6/policy.xml" "/etc/ImageMagick/policy.xml" "/usr/local/etc/ImageMagick-6/policy.xml") # 一般的なパスを追加
          POLICY_UPDATED=false
          for policy_file in "${POLICY_FILES[@]}"; do
            if [ -f "$policy_file" ]; then
              echo "Updating ImageMagick policy: $policy_file"
              # sedコマンドのエラーを避けるため、ファイルが存在する場合のみ実行し、sudoで実行
              sudo sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' "$policy_file"
              sudo sed -i 's/rights="none" pattern="PS"/rights="read|write" pattern="PS"/' "$policy_file"
              sudo sed -i 's/rights="none" pattern="EPS"/rights="read|write" pattern="EPS"/' "$policy_file"
              sudo sed -i 's/rights="none" pattern="XPS"/rights="read|write" pattern="XPS"/' "$policy_file"
              # SVGとVIDEOも追加（MoviePyで使われる可能性があるため）
              sudo sed -i 's/rights="none" pattern="SVG"/rights="read|write" pattern="SVG"/' "$policy_file"
              sudo sed -i 's/rights="none" pattern="VIDEO"/rights="read|write" pattern="VIDEO"/' "$policy_file"
              POLICY_UPDATED=true
              break 
            fi
          done
          if [ "$POLICY_UPDATED" = false ]; then
            echo "Warning: No ImageMagick policy file found to update. This might cause issues with PDF/video processing."
            # ここでエラーとして終了させることも検討できます。
            # exit 1
          fi

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # インストールされたライブラリのパスを明示的に追加 (デバッグ用)
          echo "PYTHONPATH=$(python -m site --user-site):$PYTHONPATH" >> $GITHUB_ENV
          echo "Installed packages:"
          pip list # インストールされたパッケージ一覧を表示

      - name: Create credentials.json from Secret
        env:
          CREDENTIALS_JSON_CONTENT: ${{ secrets.CREDENTIALS_JSON }}
        run: printf "%s" "$CREDENTIALS_JSON_CONTENT" > credentials.json

      - name: Create youtube_token.json from Secret
        env:
          TOKEN_JSON_CONTENT: ${{ secrets.YOUTUBE_TOKEN_JSON }}
        run: printf "%s" "$TOKEN_JSON_CONTENT" > youtube_token.json
      
      - name: Run YouTube upload script
        env:
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          PYTHONIOENCODING: "utf-8"
          # PYTHONPATH は $GITHUB_ENV 経由で次のステップに引き継がれる
        run: |
          echo "Current PYTHONPATH: $PYTHONPATH" # PYTHONPATHの内容を表示
          python main.py

      - name: Clean up temporary files
        if: always() # 常に実行 (成功時も失敗時も)
        run: |
          rm -f credentials.json youtube_token.json
          rm -rf generated_videos # 生成された動画を削除
          echo "Temporary files cleaned up."
